schema_version = "1.0.0"
id = "ccustomnodes"
version = "1.0.1"
name = "Object Utility Nodes"
tagline = "Custom nodes in new node editor"
maintainer = "Christian Coppes"
type = "add-on"
tags = ["Node"]
blender_version_min = "4.2.0"

# website = ""
license = [
  "SPDX:GPL-3.0-or-later",
]

platforms = ["windows-x64", "macos-arm64", "linux-x64"]
wheels = [
   "./wheels/pillow-11.2.1-cp311-cp311-macosx_11_0_arm64.whl",
   "./wheels/pillow-11.2.1-cp311-cp311-manylinux_2_28_x86_64.whl",
   "./wheels/pillow-11.2.1-cp311-cp311-win_amd64.whl",
]

[permissions]
files = "Save colorwheel pictures from/to temp folder"

[build]
paths_exclude_pattern = [
   "__pycache__/",
   "/.git/",
   "/*.zip",
   "README.md",
   ".gitignore",
   "/screenshots/",
   "CustomNodesSample.blend"
]


